# Generated by Django 4.1.5 on 2023-01-06 17:21

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pruduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now=True, verbose_name="Data criação"),
                ),
                (
                    "modified",
                    models.DateField(auto_now=True, verbose_name="Data alteração"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Preço"
                    ),
                ),
                ("estoque", models.IntegerField(verbose_name="Estoque")),
                (
                    "imagem",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        upload_to="produtos",
                        variations={"thumb": (125, 125)},
                        verbose_name="imagem",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=100, verbose_name="slug"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
