# Generated by Django 4.1.5 on 2023-01-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Pruduto", new_name="Produto",),
    ]
